config/routes.rb
Watermarker::Application.routes.draw do
  resources :accounts

  resources :watermarks

  root to: 'shops#index'

  resources :shops do
    resources :watermarks
  end
  resources :images

  resources :users

  resource  :session do
    collection do
      get :autologin
    end
  end

  get '/install',     to: 'insales_app#install',   as: :install
  get '/uninstall',   to: 'insales_app#uninstall', as: :uninstall
  get '/login',       to: 'sessions#create',       as: :login
  get '/logout',      to: 'sessions#destroy',      as: :logout

end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id                     :integer          not null, primary key
#  domain                 :string(255)
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  watermark_file_name    :string(255)
#  watermark_content_type :string(255)
#  watermark_file_size    :integer
#  watermark_updated_at   :datetime
#

class Shop < ActiveRecord::Base

  has_many :watermarks
  has_many :images

  accepts_nested_attributes_for :watermarks, allow_destroy: true, :reject_if => proc { |attrs| attrs['picture'].blank? }
  accepts_nested_attributes_for :images, allow_destroy: true, :reject_if => proc { |attrs| attrs['picture'].blank? }

  def watermark_path
    Rails.root.join('public').to_s + watermarks.first.picture(:original).split('?')[0]
  end

  def watermark
    watermarks.first.picture(:small).split('?')[0]
  end

  def authorize
     MyApp.configure_api domain, password
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
    @shop.watermarks.build if @shop.watermarks.blank?
    @shop.images.build if @shop.images.blank?
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shop }
      else
        format.html { render action: 'new' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:domain, :name, watermarks_attributes: [:picture], images_attributes: [:picture])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
= form_for(@shop, html: {class:"form-horizontal", role: "form"})  do |f|
  - if @shop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      ul
        - @shop.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :domain, 'Домен', class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :domain, class: 'form-control'
  .form-group
    = f.label :name, 'Название', class: 'col-sm-2 control-label'
    .col-sm-3
      = f.text_field :name, class: 'form-control'
  /= debug @shop.watermarks
  /- if @shop.watermarks.present?
  /  = image_tag @shop.watermarks.first.picture(:small)
  /- else
  = f.fields_for :watermarks do |s|
    .form-group
      = s.label :picture, 'Водяной знак', class: 'col-sm-2 control-label'
      = s.file_field :picture, class: 'col-sm-3'


  .form-group
    .col-sm-offset-2.col-sm-10
      .actions = f.submit 'Сохранить', class: 'btn btn-success btn-default'

app/views/shops/edit.html.slim
h1 Редактирование магазина

== render 'form'

= link_to 'Назад', shops_path, class: 'btn btn-primary btn-default'

app/views/shops/index.html.slim
h1 Список магазинов

table.table.table-striped style=( 'width: 65%;' )
  tr
    th Название
    th Домен
    th style=( 'width: 165px;' )
    th style=( 'width: 60px;' )

  - @shops.each do |shop|
    tr
      td = link_to shop.name, shop
      td = shop.domain
      td = link_to 'Редактировать', edit_shop_path(shop), class: 'btn btn-warning btn-default'
      td = link_to 'Удалить', shop, data: {:confirm => 'Вы уверены?'}, :method => :delete, class: 'btn btn-danger btn-default'

br

= link_to 'Новый магазин', new_shop_path, class: 'btn btn-info btn-default'

app/views/shops/new.html.slim
h1 Новый магазин

== render 'form'

= link_to 'Назад', shops_path, class: 'btn btn-primary btn-default'

app/views/shops/show.html.slim
/coffee:
/  $ ->
/    $('#image_picture').on 'change', ->
/      alert $(this).val()
p#notice = notice

p
  strong Название:
  = @shop.name

p
  strong Домен:
  = @shop.domain

p
  strong Водяные знаки:
  - @shop.watermarks.each do |watermark|
    p= image_tag watermark.picture(:small), width: 100
hr
- @shop.images.each do |image|
  .row
    .col-md-5
      .thumbnail
        = image_tag image.picture(:original)
    .col-md-5
      .thumbnail
        = image_tag image.picture(:medium)

= form_for Image.new do |f|
  .form-group
    = f.label :picture, 'Изображение', class: 'col-sm-2 control-label'
    = f.file_field :picture, class: 'col-sm-3'
    = text_field_tag :watermark, @shop.watermark_path, class: 'form-control'
  = f.submit 'Сохранить', class: 'btn btn-success btn-default'
br
br
= link_to 'Редактировать', edit_shop_path(@shop), class: 'btn btn-warning btn-default'
'
= link_to 'Назад', shops_path, class: 'btn btn-primary btn-default'