config/routes.rb
Watermarker::Application.routes.draw do
  resources :accounts

  resources :watermarks

  root to: 'shops#index'

  resources :shops do
    resources :watermarks
  end
  resources :images

  resources :users

  resource  :session do
    collection do
      get :autologin
    end
  end

  get '/install',     to: 'insales_app#install',   as: :install
  get '/uninstall',   to: 'insales_app#uninstall', as: :uninstall
  get '/login',       to: 'sessions#create',       as: :login
  get '/logout',      to: 'sessions#destroy',      as: :logout

end

app/models/watermark.rb
# == Schema Information
#
# Table name: watermarks
#
#  id                   :integer          not null, primary key
#  shop_id              :integer
#  created_at           :datetime
#  updated_at           :datetime
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Watermark < ActiveRecord::Base
  belongs_to :shop

  has_attached_file :picture,
                    styles: {
                              medium: { geometry: '100x100>'},
                              small:  { geometry: '50x50>'}
                            }
  validates_attachment_content_type :picture, :content_type => ['image/gif', 'image/jpeg', 'image/png', 'image/x-ms-bmp']
end

app/controllers/watermarks_controller.rb
class WatermarksController < ApplicationController
  before_action :set_watermark, only: [:show, :edit, :update, :destroy]

  # GET /watermarks
  # GET /watermarks.json
  def index
    @watermarks = Watermark.all
  end

  # GET /watermarks/1
  # GET /watermarks/1.json
  def show
  end

  # GET /watermarks/new
  def new
    @watermark = Watermark.new
  end

  # GET /watermarks/1/edit
  def edit
  end

  # POST /watermarks
  # POST /watermarks.json
  def create
    @watermark = Watermark.new(watermark_params)

    respond_to do |format|
      if @watermark.save
        format.html { redirect_to @watermark, notice: 'Watermark was successfully created.' }
        format.json { render action: 'show', status: :created, location: @watermark }
      else
        format.html { render action: 'new' }
        format.json { render json: @watermark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watermarks/1
  # PATCH/PUT /watermarks/1.json
  def update
    respond_to do |format|
      if @watermark.update(watermark_params)
        format.html { redirect_to @watermark, notice: 'Watermark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @watermark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watermarks/1
  # DELETE /watermarks/1.json
  def destroy
    @watermark.destroy
    respond_to do |format|
      format.html { redirect_to watermarks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watermark
      @watermark = Watermark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watermark_params
      params.require(:watermark).permit(:shop_id)
    end
end

app/helpers/watermarks_helper.rb
module WatermarksHelper
end

app/views/watermarks/_form.html.slim
= form_for @watermark do |f|
  - if @watermark.errors.any?
    #error_explanation
      h2 = "#{pluralize(@watermark.errors.count, "error")} prohibited this watermark from being saved:"
      ul
        - @watermark.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :shop
    = f.text_field :shop
  .actions = f.submit 'Save'

app/views/watermarks/edit.html.slim
h1 Editing watermark

== render 'form'

= link_to 'Show', @watermark
'|
= link_to 'Back', watermarks_path

app/views/watermarks/index.html.slim
h1 Listing watermarks

table
  tr
    th Shop
    th
    th
    th

  - @watermarks.each do |watermark|
    tr
      td = watermark.shop
      td = link_to 'Show', watermark
      td = link_to 'Edit', edit_watermark_path(watermark)
      td = link_to 'Destroy', watermark, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Watermark', new_watermark_path

app/views/watermarks/new.html.slim
h1 New watermark

== render 'form'

= link_to 'Back', watermarks_path

app/views/watermarks/show.html.slim
p#notice = notice

p
  strong Shop:
  = @watermark.shop

= link_to 'Edit', edit_watermark_path(@watermark)
'|
= link_to 'Back', watermarks_path