config/routes.rb
Watermarker::Application.routes.draw do
  resources :accounts

  resources :watermarks

  root to: 'shops#index'

  resources :shops do
    resources :watermarks
  end
  resources :images

  resources :users

  resource  :session do
    collection do
      get :autologin
    end
  end

  get '/install',     to: 'insales_app#install',   as: :install
  get '/uninstall',   to: 'insales_app#uninstall', as: :uninstall
  get '/login',       to: 'sessions#create',       as: :login
  get '/logout',      to: 'sessions#destroy',      as: :logout

end

app/models/account.rb
class Account < ActiveRecord::Base

  validates_presence_of :insales_id, :insales_subdomain, :password


  def authorize
     MyApp.configure_api insales_subdomain, password
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:insales_subdomain, :insales_id, :password)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.slim
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      h2 = "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      ul
        - @account.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :insales_subdomain
    = f.text_area :insales_subdomain
  .field
    = f.label :insales_id
    = f.number_field :insales_id
  .field
    = f.label :password
    = f.text_area :password
  .actions = f.submit 'Save'

app/views/accounts/edit.html.slim
h1 Editing account

== render 'form'

= link_to 'Show', @account
'|
= link_to 'Back', accounts_path

app/views/accounts/index.html.slim
h1 Listing accounts

table
  thead
    tr
      th Insales subdomain
      th Insales
      th Password
      th
      th
      th

  tbody
    - @accounts.each do |account|
      tr
        td = account.insales_subdomain
        td = account.insales_id
        td = account.password
        td = link_to 'Show', account
        td = link_to 'Edit', edit_account_path(account)
        td = link_to 'Destroy', account, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.slim
h1 New account

== render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
p#notice = notice

p
  strong Insales subdomain:
  = @account.insales_subdomain
p
  strong Insales:
  = @account.insales_id
p
  strong Password:
  = @account.password

= link_to 'Edit', edit_account_path(@account)
'|
= link_to 'Back', accounts_path